const projects = [
  {
    id: 1,
    title: "تطبيق بث الأفلام",
    description:
      "تطبيق متكامل لبث الأفلام مع ميزات متقدمة مثل البحث المتطور وقوائم المشاهدة الشخصية ودعم تعدد اللغات ونظام المصادقة. مبني باستخدام Next.js وReact وTailwind CSS",
    image: "/images/projects/movie-streaming/main.png",
    images: [
      "/images/projects/movie-streaming/main.png",
      "/images/projects/movie-streaming/image-1.png",
      "/images/projects/movie-streaming/image.png",
      "/images/projects/movie-streaming/image-2.png",
      "/images/projects/movie-streaming/image-3.png",
      "/images/projects/movie-streaming/image-4.png",
      "/images/projects/movie-streaming/image-5.png",
      "/images/projects/movie-streaming/image-6.png",
      "/images/projects/movie-streaming/image-7.png",
      "/images/projects/movie-streaming/image-8.png",
      "/images/projects/movie-streaming/image-9.png",
      "/images/projects/movie-streaming/image-10.png",
      "/images/projects/movie-streaming/image-11.png",
      "/images/projects/movie-streaming/image-12.png",
      "/images/projects/movie-streaming/image-13.png",
    ],

    category: "تطبيق ويب",
    link: "https://github.com/ahmedalsanadi/Movie-Streaming-App",
    liveLink: "https://movie-streaming-app-virid.vercel.app",
    tags: ["Next.js", "React", "Tailwind CSS", "Firebase", "i18n"],
  },
  {
    id: 2,
    title: "منصة التوظيف بيكسل",
    description:
      "تطبيق ويب مبني بـ Laravel لإدارة الوظائف والتقديم عليها، يتضمن ملفات تعريف لأصحاب العمل، وأوصاف وظيفية مفصلة، ووظائف التقديم. مبني باستخدام Laravel وTailwind CSS",
    image: "/images/projects/pixel-jobs/main.png",
    images: [
      "/images/projects/pixel-jobs/1.png",
      "/images/projects/pixel-jobs/2.png",
      "/images/projects/pixel-jobs/3.png",
      "/images/projects/pixel-jobs/4.png",
      "/images/projects/pixel-jobs/5.png",
      "/images/projects/pixel-jobs/6.png",
      "/images/projects/pixel-jobs/7.png",
      "/images/projects/pixel-jobs/8.png",
    ],
    category: "تطبيق ويب",
    link: "https://github.com/ahmedalsanadi/Pixel-Job-App-Site",
    liveLink: "",
    tags: ["Laravel", "PHP", "Tailwind CSS", "MySQL"],
  },
  {
    id: 3,
    title: "صفحة بيكاس",
    description:
      "صفحة هبوط حديثة لأداة إنتاجية، تتميز بتصميم نظيف وتنقل سهل. تسلط الضوء على قيمة المنصة من خلال شعارات العملاء والميزات الأساسية",
    image: "/images/projects/biccas/main.png",
    images: [
      "/images/projects/biccas/main.png",
      "/images/projects/biccas/2.png",
      "/images/projects/biccas/3.png",
      "/images/projects/biccas/4.png",
      "/images/projects/biccas/5.png",
      "/images/projects/biccas/6.png",
      "/images/projects/biccas/7.png",
      "/images/projects/biccas/8.png",
    ],
    category: "صفحة هبوط",
    link: "https://github.com/ahmedalsanadi/Biccas-Landing-Page-Ahmed-Al-Sanadi",
    liveLink:
      "https://ahmedalsanadi.github.io/Biccas-Landing-Page-Ahmed-Al-Sanadi/",
    tags: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: 4,
    title: "لوحة تحكم فينبيز المالية",
    description:
      "لوحة تحكم مالية مبنية على React تتميز برسوم بيانية تفاعلية (Chart.js)، وحركات سلسة (AOS)، وتصميم متجاوب (Tailwind CSS) لتحسين تجربة المستخدم",
    image: "/images/projects/finBiz/main.png",
    images: [
      "/images/projects/finBiz/main.png",
      "/images/projects/finBiz/1.png",
      "/images/projects/finBiz/2.png",
      "/images/projects/finBiz/3.png",
      "/images/projects/finBiz/4.png",
      "/images/projects/finBiz/5.png",
      "/images/projects/finBiz/6.png",
      "/images/projects/finBiz/7.png",
      "/images/projects/finBiz/8.png",
      "/images/projects/finBiz/9.png",
    ],
    category: "لوحة تحكم",
    link: "https://github.com/ahmedalsanadi/FinBiz",
    liveLink: "https://main--finbiz-al-sanadi.netlify.app/",
    tags: ["React", "Chart.js", "Tailwind CSS", "AOS"],
  },
  {
    id: 5,
    title: "تطبيق تويتر",
    description:
      "تطبيق ويب متكامل مصمم لمحاكاة الوظائف الأساسية لمنصة التواصل الاجتماعي الشهيرة تويتر",
    image: "/images/projects/twitter-app/main.png",
    images: [
      "/images/projects/twitter-app/main.png",
      "/images/projects/twitter-app/1.png",
      "/images/projects/twitter-app/2.png",
      "/images/projects/twitter-app/3.png",
      "/images/projects/twitter-app/4.png",
      "/images/projects/twitter-app/5.png",
      "/images/projects/twitter-app/6.png",
      "/images/projects/twitter-app/7.png",
      "/images/projects/twitter-app/8.png",
    ],
    category: "تطبيق ويب",
    link: "https://github.com/ahmedalsanadi/twitter-app",
    liveLink: "https://twitter-2n7ic2inc-ahmedalsanadis-projects.vercel.app/",
    tags: [
      "TypeScript",
      "React",
      "Next.js",
      "Tailwind CSS",
      "Prisma",
      "MongoDB",
    ],
  },
];

export default projects;
